source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'LocoMotive' do

    #pod 'AlamofireObjectMapper', '~> 4.0'
	pod 'Alamofire', '~> 4.4'
    pod 'SwiftyJSON'
	pod 'SocketRocket'
    pod 'SVProgressHUD'
end
